repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.3.0
    hooks:
      - id: check-yaml
      - id: end-of-file-fixer
      - id: check-json
      - id: pretty-format-json
        args:
          - --autofix
          - --indent=4
          - --no-ensure-ascii
          - --no-sort-keys
      - id: check-merge-conflict
      - id: detect-aws-credentials
      - id: detect-private-key
      - id: trailing-whitespace
        exclude: '^.+\.md$'
  - repo: https://github.com/pre-commit/mirrors-prettier
    rev: v3.0.1
    hooks:
      - id: prettier
  - repo: https://github.com/psf/black
    rev: 23.7.0
    hooks:
      - id: black
  - repo: https://github.com/alan-turing-institute/CleverCSV-pre-commit
    rev: v0.8.0 # or any later version
    hooks:
      - id: clevercsv-standardize
